name: Update README Stats
on:
  schedule:
    - cron: "0 0 * * *" # Runs every night at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=Hridoykhan4&show_icons=true&theme=tokyonight&hide_border=true
      - name: Generate Top Langs Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=Hridoykhan4&layout=compact&theme=tokyonight&hide_border=true
      - name: Push to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update GitHub stats" || exit 0
          git push